#!/data/data/com.termux/files/usr/bin/bash

source /data/data/com.termux/files/home/bin/tmenu.sh

#tmenu -c aaa bbb -cns ccc -s

#			FG(N)	BG(N)	FG(L)	BG(L)
#	Black	30		40		90		100
#	Red		31		41		91		101
#	Green	32		42		92		102
#	Yellow	33		43		93		103
#	Blue	34		44		94		104
#	Magenta	35		45		95		105
#	Cyan	36		46		96		106
#	White	37		47		97		107

WDIR="$(pwd)"
ESC_KEY=$'\033'
ERROR_COLOR=91
CMD_COLOR=96

if [[ ! -z "$1" ]]; then
	while IFS= read -r line; do
		if [[ -z "$TCMD_DST" ]]; then
			TCMD_DST="$line"
		else TCMD_SRC="$line"
		fi
	done < "$1"
	unset IFS
	echo "$(date +"%x %X") :: $TCMD_SRC" >> ~/.tfe_history
fi

runCmd() {
	eval "$1"
	if [[ $? != 0 ]]; then
		TFE_ERR+=( "$1" )
	fi
}

tmenu.fileExplorer() {
	SRC="$(pwd)"
	local title=""
	local prevItem=""

	until [[ "$TMENU_RESULT" == "EXIT" ]]; do
		local file_list=( "." ".." )
		local checkPrev=0

		if [[ -z "$1" ]]; then
			title="\033[47m\033[30m File explorer \033[0m\n---------------\n\n$(pwd)\n(0: Action | 1: Directory)\n\n"
		elif [[ "$1" == "slDst" ]]; then
			title="\033[44m Select Destination \033[0m\n--------------------\n\n$(pwd)\n(0: Select)\n\n"
		fi

		for file in *; do
			if [[ -d "$file" ]]; then
				file_list+=( "$file" )
			fi
			if [[ "$prevItem" == "$file" ]]; then
				checkPrev=1
			fi
		done

		for file in *; do
			if [[ -f "$file" ]]; then
				file_list+=( "$file" )
			fi
		done

		clear
		printf "$title"

		if [[ -z "$prevItem" || ! -z "$prevItem" && $checkPrev == 0 ]]; then
			if [[ ! -z "${file_list[2]}" ]]; then
				prevItem=${file_list[2]}
			else
				prevItem=".."
			fi
		fi
		
		tmenu "$prevItem" "${file_list[@]}"
		
		prevItem="$MENU_SELECTED"

		if [[ "$TMENU_RESULT" == "$ESC_KEY" ]]; then
			break
		elif [[ "$TMENU_RESULT" == 0 ]]; then
			if [[ "$1" == "slDst" ]]; then
				DST="$(pwd)"
				TMENU_RESULT="$(pwd)"
				break
			elif [[ -d "$MENU_SELECTED" ]]; then
				action.dir "$MENU_SELECTED"
			elif [[ -f "$MENU_SELECTED" ]]; then
				action.file "$MENU_SELECTED"
			fi
		elif [[ "$TMENU_RESULT" == "." ]]; then
			action.dir "$TMENU_RESULT"
		elif [[ -d "$TMENU_RESULT" ]]; then
			cd "$TMENU_RESULT" 
			WDIR="$(pwd)"
			if [[ -z "$1" ]]; then
				SRC="$(pwd)"
			fi
			unset prevItem
		elif [[ -f "$TMENU_RESULT" ]]; then
			action.file "$TMENU_RESULT"
		fi
	done
	if [[ "$1" == "slDst" ]]; then
		cd "$SRC"
	fi
}

action.dir() {
	echo "Directory Action"
	echo "----------------"
	echo

	local actions=( "Copy to TCMD" "Copy" )
	if [[ ! -z "$DST" ]]; then
		local prevDST="$(basename "$DST")"
		actions+=( "Copy to \"$prevDST\"" )
	fi
	actions+=( "Delete" "Move" "Rename" )
	if [[ -d "$1/.git" ]]; then
		actions+=( "Git" )
	fi
	actions+=( "Zip" "Zip to TCMD" "Detail" )

	tmenu "${actions[@]}"

	case "$TMENU_RESULT" in
		"Copy to TCMD")
			if [[ -z "$TCMD_DST" ]]; then
				read -rep "Destination: (cancel) " TCMD_DST
				echo
				eval TCMD_DST="$TCMD_DST"
			fi
			if [[ ! -z "$TCMD_DST" ]]; then
				cp -rf "./$1" "$TCMD_DST"
			fi
			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Copy")
			tmenu.fileExplorer "slDst"
			if [[ "$TMENU_RESULT" == "$ESC_KEY" ]]; then
				local cDST=""
				read -rep "Destination: (cancel) " cDST
				echo
				eval cDST="$cDST"
				if [[ ! -z "$cDST" ]]; then
					cp -rf "./$1" "$cDST"
				fi
			else
				cp -rf "./$1" "$DST"
			fi

			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Copy to \"$prevDST\"")
			cp -rf "./$1" "$DST"
			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Delete")
			local msg=""
			local dotOpt=""

			if [[ "$1" == "." ]]; then
				msg="Delete **All**? (y/N): "
			else msg="Delete \"$1\"? (y/N): "
			fi

			read -rn1 -p "$msg" key
			echo
			echo

			if [[ "$key" == "y" || "$key" == "Y" ]]; then
				if [[ "$1" == "." ]]; then
          			dotOpt=$(shopt -p dotglob)
          			dotOpt=${dotOpt:7:1}
					if [[ "$dotOpt" == "u" ]]; then
						shopt -s dotglob
						rm -rf ./*
					else rm -rf ./*
					fi
				else rm -rf "./$1"
				fi

				if [[ "$?" != 0 ]]; then
					echo
					read -rsn1 -p "Press any key to continue..." key
				else unset prevItem
				fi

				if [[ "$dotOpt" == "u" ]]; then
					shopt -u dotglob
				fi
			fi
			;;

		"Move")
			tmenu.fileExplorer "slDst"
			if [[ "$TMENU_RESULT" == "$ESC_KEY" ]]; then
				local mDST=""
				read -rep "Destination: (cancel) " mDST
				echo
				eval mDST="$mDST"
				if [[ ! -z "$mDST" ]]; then
					mv "./$1" "$mDST"
				fi
			else
				mv "./$1" "$DST"
			fi

			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Rename")
			local newName=""
			read -rep "New name: (cancel) " newName
			echo
			eval newName="$newName"
			if [[ ! -z "$newName" ]]; then
				mv "./$1" "$newName"
			fi

			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Git")
			local cMsg=""
			cd "$1"
			read -rn1 -p "(p)ull/(P)ush? " key
			echo

			if [[ -z "$key" || "$key" == "P" ]]; then
				read -rep "Message: (cancel) " cMsg
				echo
				if [[ ! -z "$cMsg" ]]; then
					git add .
					git commit -m "$cMsg"
					git push
					echo
					read -rsn1 -p "Press any key to continue..." key
				fi
			elif [[ "$key" == "p" ]]; then
				echo
				git pull
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi

			cd "$WDIR"
			;;

		"Zip")
			local zDst
			read -rep "Archive name: " zDst
			eval zDst="$zDst"
			7zz a -snl "$zDst" "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Zip to TCMD")
			local zDst
			if [[ -z "$TCMD_DST" ]]; then
				read -rep "Directory Path: " TCMD_DST
			fi
			read -rep "Archive name: " zDst
			eval zDst="$TCMD_DST$zDst"
			7zz a -snl "$zDst" "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Detail")
			echo "Directory Detail"
			echo "----------------"
			echo
			echo "Size: $(du -sh "$1")"
			echo
			ls -lh "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;
	esac
}

action.file() {
	declare -a actions
	echo "File Action"
	echo "-----------"
	echo

	actions=( "Copy to TCMD" "Copy" )
	if [[ ! -z "$DST" ]]; then
		local prevDST="$(basename "$DST")"
		actions+=( "Copy to \"$prevDST\"" )
	fi
	actions+=( "Delete" "Move" "Rename" "Edit" )
	if [[ -x "$1" ]]; then
		actions+=( "Run" )
	fi

	case "$1" in
		*".zip"|*".7z"|*".gz"|*".xz"|*".tar"|*".rar")
			actions+=( "Extract" )
			;;

		*".sh")
			if [[ ! -x "$1" ]]; then
				actions+=( "Run Shell" )
			fi
			;;

		*".js"|*".cjs"|*".mjs")
			actions+=( "Run Node.js" "Run NodeMon" )
			;;

		*".class")
			actions+=( "Run Java" )
			;;

		*".java")
			actions+=( "Compile Java" )
			;;
	esac

	actions+=( "Detail" )

	tmenu "${actions[@]}"

	case "$TMENU_RESULT" in
		"Copy to TCMD")
			if [[ -z "$TCMD_DST" ]]; then
				read -rep "Destination: (cancel) " TCMD_DST
				echo
				eval TCMD_DST="$TCMD_DST"
			fi
			if [[ ! -z "$TCMD_DST" ]]; then
				cp -f "./$1" "$TCMD_DST"
			fi
			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Copy")
			local cDST=""
			tmenu.fileExplorer "slDst"
			if [[ "$TMENU_RESULT" == "$ESC_KEY" ]]; then
				read -rep "Destination: (cancel) " cDST
				echo
				eval cDST="$cDST"
				if [[ ! -z "$cDST" ]]; then
					cp -f "./$1" "$cDST"
				fi
			else
				cp -f "./$1" "$DST"
			fi

			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Copy to \"$prevDST\"")
			cp -f "./$1" "$DST"
			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Delete")
			local msg="Delete \"$1\"? (y/N): "
			read -rn1 -p "$msg" key
			echo
			echo

			if [[ "$key" == "y" || "$key" == "Y" ]]; then
				rm -f "./$1"
				if [[ "$?" != 0 ]]; then
					echo
					read -rsn1 -p "Press any key to continue..." key
				else unset prevItem
				fi
			fi
			;;

		"Move")
			tmenu.fileExplorer "slDst"
			if [[ "$TMENU_RESULT" == "$ESC_KEY" ]]; then
				local mDST=""
				read -rep "Destination: (cancel) " mDST
				echo
				eval mDST="$mDST"
				if [[ ! -z "$mDST" ]]; then
					mv "./$1" "$mDST"
				fi
			else
				mv "./$1" "$DST"
			fi

			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Rename")
			local newName=""
			read -rep "New name: (cancel) " newName
			echo
			eval newName="$newName"
			if [[ ! -z "$newName" ]]; then
				mv "./$1" "$newName"
			fi

			if [[ $? -ne 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"Edit")
			vim "$1"
			;;

		"Run")
			"./$1"
			;;

		"Extract")
			local zDst
			read -rep "Destination: " zDst
			eval zDst="$zDst"
			7zz x -o"$zDst" "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Run Shell")
			bash "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Run Node.js")
			node "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Run NodeMon")
			nodemon "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Run Java")
			java "${1:0: -6}"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Compile Java")
			javac "$1" && java "${1:0: -5}"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"Detail")
			echo "File Detail"
			echo "----------------"
			echo
			echo "Size: $(du -sh "$1")"
			echo
			ls -lh "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;
	esac
}

until [[ "$TMENU_RESULT" == "EXIT" ]]; do
	clear
	echo "           ##############################           "
	echo "           #                            #           "
	echo "           #     TERMUX FILE EDITOR     #           "
	echo "           #                            #           "
	echo "           ##############################           "
	echo

	tmenu "1. File explorer" "2. HASH check" "3. Backup document" "4. Backup Vim" "5. Vim" "6. History" "7. Exit"

	case "$TMENU_RESULT" in
		"1. File explorer") tmenu.fileExplorer ;;

		"2. HASH check")
			if [[ -z "$TCMD_SRC" ]]; then
				read -rep "File path: " TCMD_SRC
				eval TCMD_SRC="$TCMD_SRC"
			fi

			until [[ "$TMENU_RESULT" == "EXIT" ]]; do
				clear
				echo "HASH check"
				echo "----------"
				echo
				tmenu "1. SHA1" "2. SHA256" "3. SHA384" "4. SHA512" "5. MD5" "6. Back"

				case "$TMENU_RESULT" in
					"1. SHA1")
						echo === SHA1 ===
						sha1sum "$TCMD_SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;

					"2. SHA256")
						echo === SHA256 ===
						sha256sum "$TCMD_SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;
					
					"3. SHA384")
						echo === SHA384 ===
						sha384sum "$TCMD_SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;
					
					"4. SHA512")
						echo === SHA512 ===
						sha512sum "$TCMD_SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;
					
					"5. MD5")
						echo === MD5 ===
						md5sum "$TCMD_SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;

					"6. Back" | "$ESC_KEY")
						unset TMENU_RESULT
						break
						;;

					"0" | "$ESC_KEY")
						unset TMENU_RESULT
						break
						;;
				esac
			done
			;;

		"3. Backup document")
			cd "$HOME/docs"
			git add .
			git commit -m "update"
			git push
			cd "$WDIR"
			echo
			read -rsn1 -p "Press ESC to exit, other keys to continue..." key
			echo
			echo
			if [[ "$key" == "$ESC_KEY" ]]; then
				exit
			fi
			;;

		"4. Backup Vim")
			TFE_ERR=()
			rm -rf "$TMPDIR/vim" 2> /dev/null
			runCmd "mkdir -p '$TMPDIR/vim/.config/coc' '$TMPDIR/vim/.vim/plugged/coc.nvim/plugin' '$TMPDIR/vim/bin'"
			runCmd "cp -rf '$HOME/.config/coc/ultisnips' '$TMPDIR/vim/.config/coc'"
			runCmd "cp -rf '$HOME/.vim/plugged/coc.nvim/plugin/coc.vim' '$TMPDIR/vim/.vim/plugged/coc.nvim/plugin'"
			runCmd "find '$HOME/bin' -mindepth 1 -maxdepth 1 ! -name '.git' -a ! -name 'vim.zip' -exec cp -rf '{}' '$TMPDIR/vim/bin' \;"
			runCmd "7zz a -snl -y '/storage/emulated/0/Backup/Apps/vim.zip' '$TMPDIR/vim/.' '$HOME/.termux' '$HOME/.vimrc' '$HOME/.gitconfig' '$HOME/nodemon.json' '$HOME/.bashrc'"
			runCmd "cp -rf '/storage/emulated/0/Backup/Apps/vim.zip' '$HOME/bin'"
			runCmd "rm -rf '$TMPDIR/vim'"
			echo
			printf ">>>>>>>>>> \033[44m %s \033[0m <<<<<<<<<<\n" "Git Push Update"
			echo
			read -rep "Message: (cancel) " cMsg
			echo

			if [[ ! -z "$cMsg" ]]; then
				cd "$HOME/bin"
				git add .
				git commit -m "$cMsg"
				runCmd "git push"
				cd "$WDIR"
			else echo "Git push cancelled!"
			fi

			if [[ ${#TFE_ERR[@]} > 0 ]]; then
				echo
				printf "\033[41m%s\033[93m%s\033[0m\033[41m%s\033[0m\n" "Total " "${#TFE_ERR[@]}" " error when backup:"
				for errCmd in "${TFE_ERR[@]}"; do
					[[ $errCmd =~ (^[a-zA-Z0-9]+)" "(.*) ]]
					cmd="${BASH_REMATCH[1]}"
					params="${BASH_REMATCH[2]}"
					if [[ ${#params} -gt 40 ]]; then
						params="${params:0:26}... ${params: -10}"
					fi
					printf "\t\033[%sm$cmd\033[0m $params\n" $CMD_COLOR
				done
			fi
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"5. Vim") vim ;;

		"6. History")
			cat ~/.tfe_history
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"7. Exit" | "0" | "$ESC_KEY") exit ;;
	esac
done

