#!/data/data/com.termux/files/usr/bin/bash

source /data/data/com.termux/files/home/bin/tmenu.sh

WDIR="$(pwd)"
ESC_KEY=$'\033'

if [[ ! -z "$1" ]]; then
	while IFS= read -r line; do
		if [[ -z "$DST" ]]; then
			DST="$line"
		else SRC="$line"
		fi
	done < "$1"
	unset IFS
	echo "$(date +"%x %X") :: $SRC" >> ~/.tfe_history
fi

action.dir() {
	echo "Directory Action"
	echo "----------------"
	echo
	tmenu "1. Copy to TCMD" "2. Copy" "3. Delete" "4. Git" "5. Zip" "6. Zip to TCMD" "7. Detail"
	case "$TMENU_RESULT" in
		"1. Copy to TCMD")
			if [[ -z "$DST" ]]; then
				read -rep "Destination: " DST
				echo
				eval DST="$DST"
			fi
			cp -r "$1" "$DST"
			if [[ "$?" != 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"2. Copy")
			local cpDst
			read -rep "Destination: " cpDst
			echo
			eval cpDst="$cpDst"
			cp -r "$1" "$cpDst"
			if [[ "$?" != 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"3. Delete")
			read -rn1 -p "Delete \"$1\"? (y/N): " key
			echo
			echo
			if [[ "$key" == "y" || "$key" == "Y" ]]; then
				rm -rf "$1"
			fi
			if [[ "$?" != 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			else unset prevItem
			fi
			;;

		"4. Git")
			local cMsg
			cd "$1"
			read -rep "Message: " cMsg
			echo
			git add .
			git commit -m "$cMsg"
			git push
			cd "$WDIR"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"5. Zip")
			local zDst
			read -rep "Archive name: " zDst
			eval zDst="$zDst"
			7zz a -snl "$zDst" "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"6. Zip to TCMD")
			local zDst
			if [[ -z "$DST" ]]; then
				read -rep "Directory Path: " DST
			fi
			read -rep "Archive name: " zDst
			eval zDst="$DST$zDst"
			7zz a -snl "$zDst" "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"7. Detail")
			echo "Directory Detail"
			echo "----------------"
			echo
			echo "Size: $(du -sh "$1")"
			echo
			ls -lh "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;
	esac
}

action.file() {
	echo "File Action"
	echo "-----------"
	echo

	if [[ "$1" == *.zip || "$1" == *.7z || "$1" == *.gz || "$1" == *.xz || "$1" == *.tar || "$1" == *.rar ]]; then
		tmenu "1. Copy to TCMD" "2. Copy" "3. Delete" "4. Edit" "5. Extract"
	else tmenu "1. Copy to TCMD" "2. Copy" "3. Delete" "4. Edit"
	fi

	case "$TMENU_RESULT" in
		"1. Copy to TCMD")
			if [[ -z "$DST" ]]; then
				read -rep "Destination: " DST
				echo
				eval DST="$DST"
			fi
			cp "$1" "$DST"
			if [[ "$?" != 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"2. Copy")
			local cpDst
			read -rep "Destination: " cpDst
			echo
			eval cpDst="$cpDst"
			cp "$1" "$cpDst"
			if [[ "$?" != 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			fi
			;;

		"3. Delete")
			read -rn1 -p "Delete \"$1\"? (y/N): " key
			echo
			echo
			if [[ "$key" == "y" || "$key" == "Y" ]]; then
				rm -f "$1"
			fi
			if [[ "$?" != 0 ]]; then
				echo
				read -rsn1 -p "Press any key to continue..." key
			else unset prevItem
			fi
			;;

		"4. Edit")
			vim "$1"
			;;

		"5. Extract")
			local zDst
			read -rep "Destination: " zDst
			eval zDst="$zDst"
			7zz x -o"$zDst" "$1"
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;
	esac
}

tmenu.create() {
	if [[ -z "$search_result" ]]; then
		tmenu "$@"
	else 
		tmenu "$search_result" "$@"
		unset search_result
	fi
}

tmenu.createDefault() {
	if [[ -z "$search_result" ]]; then
		tmenu "$@"
	else 
		tmenu "$search_result" "${@:2}"
		unset search_result
	fi
}

tmenu.fileExplorer() {
	while :; do
		local file_list=( "." ".." )
		local counter=1
		local checkPrev=0

		for file in *; do
			(( ++counter ))
			file_list[$counter]="$file"
			if [[ "$prevItem" == "$file" ]]; then
				checkPrev=1
			fi
		done

		clear
		echo "File explorer"
		echo "-------------"
		echo
		echo "$(pwd)"
		echo "(0: Action | 1: Directory)"
		echo

		if [[ ! -z "$prevItem" && $checkPrev == 0 ]]; then
			unset prevItem
		fi
		
		if [[ -z "$prevItem" ]]; then
			local prevItem=${file_list[2]}
		fi

		tmenu "$prevItem" "${file_list[@]}"
		
		prevItem="$MENU_SELECTED"

		if [[ "$TMENU_RESULT" == "$ESC_KEY" ]]; then
			break
		elif [[ "$TMENU_RESULT" == 0 ]]; then
			if [[ -d "$MENU_SELECTED" ]]; then
				action.dir "$MENU_SELECTED"
			elif [[ -f "$MENU_SELECTED" ]]; then
				action.file "$MENU_SELECTED"
			fi
		elif [[ "$TMENU_RESULT" == "." ]]; then
			action.dir "$TMENU_RESULT"
		elif [[ -d "$TMENU_RESULT" ]]; then
			cd "$TMENU_RESULT" 
			WDIR="$(pwd)"
			unset prevItem
		elif [[ -f "$TMENU_RESULT" ]]; then
			action.file "$TMENU_RESULT"
		fi
	done
}

while :; do
	clear
	echo "           ##############################           "
	echo "           #                            #           "
	echo "           #     TERMUX FILE EDITOR     #           "
	echo "           #                            #           "
	echo "           ##############################           "
	echo

	tmenu.create "1. File explorer" "2. HASH check" "3. Backup document" "4. Vim" "5. History" "6. Exit"

	case "$TMENU_RESULT" in
		"1. File explorer") tmenu.fileExplorer ;;

		"2. HASH check")
			if [[ -z "$SRC" ]]; then
				read -rep "File path: " SRC
				eval SRC="$SRC"
			fi

			while :; do
				clear
				echo "HASH check"
				echo "----------"
				echo
				tmenu "1. SHA1" "2. SHA256" "3. SHA384" "4. SHA512" "5. MD5" "6. Back"

				case "$TMENU_RESULT" in
					"1. SHA1")
						echo === SHA1 ===
						sha1sum "$SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;

					"2. SHA256")
						echo === SHA256 ===
						sha256sum "$SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;
					
					"3. SHA384")
						echo === SHA384 ===
						sha384sum "$SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;
					
					"4. SHA512")
						echo === SHA512 ===
						sha512sum "$SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;
					
					"5. MD5")
						echo === MD5 ===
						md5sum "$SRC"
						echo
						read -rsn1 -p "Press ESC to exit, other keys to continue..." key
						echo
						echo
						if [[ "$key" == "$ESC_KEY" ]]; then
							exit
						fi
						;;

					"6. Back" | "$ESC_KEY")
						unset TMENU_RESULT
						break
						;;

					"0" | "$ESC_KEY")
						unset TMENU_RESULT
						break
						;;
				esac
			done
			;;

		"3. Backup document")
			cd ~/docs
			git add .
			git commit -m "update"
			git push
			cd $WDIR
			echo
			read -rsn1 -p "Press ESC to exit, other keys to continue..." key
			echo
			echo
			if [[ "$key" == "$ESC_KEY" ]]; then
				exit
			fi
			;;

		"4. Vim") vim ;;

		"5. History")
			cat ~/.tfe_history
			echo
			read -rsn1 -p "Press any key to continue..." key
			;;

		"6. Exit" | "0" | "$ESC_KEY") exit ;;
	esac
done

